[package]
name = "pwned"
version = "0.1.0"
authors = ["Saaket Prakash <saaketp@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
sha-1 = "0.9.4"
